language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew clean assemble -Dpre-dex=false
  - ./gradlew app:test
  - ./gradlew lint

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

